name: CI to Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_PASS: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    steps:

      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/docker-python-gs:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
